### ISSUE TITLE
Radarr Dark theme not working at all on Radarr V4

### ISSUE THREAD

**Issue by mkanet** [ThemeParkTycoon/theme.park#508]
**Describe the bug**
The CSS style is not changing at all.

**Radarr Version:**  4.7.5.7809

**Theme Install Method** (Don't skip)
NGINZ sub_filter
```nginx
    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name radarr.mydomain.com;
        location / {
            proxy_pass http://localhost:9998;
            include ./conf/proxy.conf;
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/radarr/dark.css">
            </head>';
            sub_filter_once on;
        }
    }
```
**Screenshots**
![image](https://github.com/ThemeParkTycoon/theme.park/assets/811008/1c005437-2099-488e-9057-2fbe90187a6e)

**Desktop (If applicable) (please complete the following information):**
 - Browser: Occurs on all web browsers

**Comment by GilbN** [comment]
See docs on how the subfilter should be applied https://docs.theme-park.dev/themes/radarr/#setup

**Comment by mkanet** [comment]
> See docs on how the subfilter should be applied https://docs.theme-park.dev/themes/radarr/#setup

Thanks.  But, there still seems to be something wrong with it.  I changed the code to exactly below and deleted browser cache, but it doesn't change.  I tried on both MS Edge and Chrome.  I don't have this issue when using the Sonarr theme.park dark theme in the same fashion.

```nginx
    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name radarr.mydomain.com;
        location / {
            proxy_pass http://localhost:9998;
            proxy_set_header Accept-Encoding "";
            sub_filter 
            '<body>'
            '<body><link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/<app>/<theme>.css">';
            sub_filter_once on;
        }
    }
```

**Comment by GilbN** [comment]
Check your href

**Comment by GilbN** [comment]
And check browser console for errors

**Comment by mkanet** [comment]
@GilbN thank you so much for your patience.  It worked after I corrected the href.  Thank so much!
