### ISSUE TITLE
Aquamarine theme for TheLounge

### ISSUE THREAD

**Issue by aicynide** [ThemeParkTycoon/theme.park#510]
Transparency is dark in mobile

**Comment by GilbN** [comment]
The lounge is deprecated

**Comment by aicynide** [comment]
It officially supports custom css.
Do you have better irc client than Thelounge that you  don't need it?
Are you more into usenet leeching that you don't need irc for announce/support
 But remember source for most files are private trackers and although most new indexers have discord server, irc server for old indexers still exists
